project:
  type: website

website:
  title: "Saka Magsarjav"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts/first.qmd
        text: Blog


format:
  html:
    theme: litera
    css: styles.css
    toc: true



