---
title: "Work Clean Book Review"
draft: true
---

Main Take Away: Daily Meeze Point



## Summary

### First Course:

#### Focus

 What mise-en-place is. The idea that everything has a place and time. It is a way of life and not just in the kitchen. It is a system.

#### Choas

The three values of mise-en-place

* Preparation: The central concept of mise-en-place
* Process: Figuring out the best way (depending on the task) to get things done ("high functioning human and being happier for it")
* Presence: Being mindful

### Second Course:

The 10 main "ingredients" in implementing philosophy of mise-en-place.

#### Planning is Prime

*Commit to being honest with time. Plan Daily.*

* Planning comes first
* Taking honest time into consideration
* Proper scheduling: not only task but broken down into proper ordered steps, and necessary tools and equipment.
* Overall picture down to smaller sections
* In Practice:
    + Determining daily tasks
    + Ordering the actions into sequence
* Exercise:
    + To start make honestly log: time and log activities and task to have better understanding of how much time investment is one thing.
    + Finding Meeze Point (optimal number of actions into your daily list)
* Habits:
    + Create a Daily Meeze (A time in your schedule to declutter and plan for your next day) [Section A Day of Working Clean]
    + Schedule Actions
    + Plan "Plate First": Break complex tasks down to smaller steps and actions
    + Get there early: getting places early to help with calm and control in the situation

*Entering a space calmly, under your own control, and without apology retains your power and dignity.*



#### Arranging spaces perfecting movements

*Commit to setting your station and reducing impendiments to your movements and activities. Remove friction.*

* Gather resources: everything you need one space
* Arrange space: placement of everything to move effectively
* Training and Restrain Movements: No energy wasted
* Greet space: Utilise space
* Chain Tasks: Stacking same tasks one after another that flows
* In Practice:
    + remove resistance
* Exercise:
    + Audit Spaces and Moves:
        - List 3 tasks that are difficult or feel resistant
        - For each task list one action to decrease resistance 
    + Draw and Build Workstation
        - Draw your ideal work space
        - Question whether it makes sense in the space and why
* Habits:
    + Checklist:
        - select task
        - break in to 10 steps or less
        - test checkist using 3 times
        - once finished checklist make notes of anything that needs to be adjusted
    + Digital Declutter
     - Learn gestures
     - Automate
     - Learn to type

*We arrange spaces to remove resistance.*

#### Clean as you go

*Commit to maintaining your system. Always be cleaning.*


* Keeping organisation system no matter the chaos
* Nothing left out of cleaning system
* Keep your space clean
* Exercise:
    + Come to zero: using your planned station every hour or so reset your station
* Habits:
    + Practice Project Hygiene: Keep only the things you need, remove everything else
    + Develop repertoire of cleaning tactics: dusting wiping, straightening, containerise.





#### Making First Moves

*Commit to using time to your benefit. Start now*

* An action taken now is better than later
* Set reminders
* Immersive time  VS Process time
    + As this occurring you want to the immersive work, things that take need your attention fully during the whole time. This works will be work that happens the same amount time whether it needs to be done now or later.
    + Do the things that take short time but will "process" without your input. However, these will delay the output work by multiples such as projects that depend on other peoples inputs. 
* Exercise:
    + Determining immersive vs process by asking these questions for each project:
        - If I don't act now, do I stop a process on  my behalf?
        - Do I stop other people on my behalf?
        - If yes, then process, otherwise, immersive.
* Habits:
    + Schedule blocks of immersive and process time
        - with every task determine which it falls into
        - every day spend 30 min to block time to process work
        - alternate process vs immersive time
        - this will be determined by the type of work you do
        - schedule process time after meetings
    + Maintaining a moving and marking mentality
        - keep outsourced log of tasks that needs to be done that pop up in your head
        - set an action to every task
        - move immediately on your process work
        - mark tasks into schedule to daily meeze
        - email mangagement
        - make sure to get to the task during daily meeze

*The present has incalculably more value than the future. Starting is, in effect, a shortcut.*

