---
title: "Work Clean Book Review"
draft: true
---

Main Take Away: Daily Meeze Point



## Summary

### First Course:

#### Focus

 What mise-en-place is. The idea that everything has a place and time. It is a way of life and not just in the kitchen. It is a system.

#### Choas

The three values of mise-en-place

* Preparation: The central concept of mise-en-place
* Process: Figuring out the best way (depending on the task) to get things done ("high functioning human and being happier for it")
* Presence: Being mindful

### Second Course:

The 10 main "ingredients" in implementing philosophy of mise-en-place.

#### Planning is Prime

*Commit to being honest with time. Plan Daily.*

* Planning comes first
* Taking honest time into consideration
* Proper scheduling: not only task but broken down into proper ordered steps, and necessary tools and equipment.
* Overall picture down to smaller sections
* In Practice:
    + Determining daily tasks
    + Ordering the actions into sequence
* Exercise:
    + To start make honestly log: time and log activities and task to have better understanding of how much time investment is one thing.
    + Finding Meeze Point (optimal number of actions into your daily list)
* Habits:
    + Create a Daily Meeze (A time in your schedule to declutter and plan for your next day) [Section A Day of Working Clean]
    + Schedule Actions
    + Plan "Plate First": Break complex tasks down to smaller steps and actions
    + Get there early: getting places early to help with calm and control in the situation

*Entering a space calmly, under your own control, and without apology retains your power and dignity.*



#### Arranging spaces perfecting movements

*Commit to setting your station and reducing impendiments to your movements and activities. Remove friction.*

* Gather resources: everything you need one space
* Arrange space: placement of everything to move effectively
* Training and Restrain Movements: No energy wasted
* Greet space: Utilise space
* Chain Tasks: Stacking same tasks one after another that flows
* In Practice:
    + remove resistance
* Exercise:
    + Audit Spaces and Moves:
        - List 3 tasks that are difficult or feel resistant
        - For each task list one action to decrease resistance 
    + Draw and Build Workstation
        - Draw your ideal work space
        - Question whether it makes sense in the space and why
* Habits:
    + Checklist:
        - select task
        - break in to 10 steps or less
        - test checkist using 3 times
        - once finished checklist make notes of anything that needs to be adjusted
    + Digital Declutter
     - Learn gestures
     - Automate
     - Learn to type

*We arrange spaces to remove resistance.*

#### Clean as you go

*Commit to maintaining your system. Always be cleaning.*


* Keeping organisation system no matter the chaos
* Nothing left out of cleaning system
* Keep your space clean
* Exercise:
    + Come to zero: using your planned station every hour or so reset your station
* Habits:
    + Practice Project Hygiene: Keep only the things you need, remove everything else
    + Develop repertoire of cleaning tactics: dusting wiping, straightening, containerise.





#### Making First Moves

*Commit to using time to your benefit. Start now*

* An action taken now is better than later
* Set reminders
* Immersive time  VS Process time
    + As this occurring you want to the immersive work, things that take need your attention fully during the whole time. This works will be work that happens the same amount time whether it needs to be done now or later.
    + Do the things that take short time but will "process" without your input. However, these will delay the output work by multiples such as projects that depend on other peoples inputs. 
* Exercise:
    + Determining immersive vs process by asking these questions for each project:
        - If I don't act now, do I stop a process on  my behalf?
        - Do I stop other people on my behalf?
        - If yes, then process, otherwise, immersive.
* Habits:
    + Schedule blocks of immersive and process time
        - with every task determine which it falls into
        - every day spend 30 min to block time to process work
        - alternate process vs immersive time
        - this will be determined by the type of work you do
        - schedule process time after meetings
    + Maintaining a moving and marking mentality
        - keep outsourced log of tasks that needs to be done that pop up in your head
        - set an action to every task
        - move immediately on your process work
        - mark tasks into schedule to daily meeze
        - email mangagement
        - make sure to get to the task during daily meeze

*The present has incalculably more value than the future. Starting is, in effect, a shortcut.*



#### Finishing Actions

*Commit to delivering. When a task is nearly done, finish it. Always be unblocking*

* Finishing the task completely: 90% done is the same as 0% done
* Avoiding hidden costs of stopping: aggregate alike actions, stopping costs and starting up again costs.
* Completely finishing a task clears the workspace and headspace
* Don't start something you cannot finish; Finishing is not just complete the whole task it is about taking the extra time to make starting again easier.
* Exercises:
    + Categorising tasks into ease and expectations.
    + High expectation and high ease are finishables.
    + Low expectation and low ease are delayable
    + low expectataion and high ease are distracting
    + high expectation and low ease are complex tasks that need scheduling
* Habits:
    + Why we stop and strategies for continuing
        - Fatigue drains us so rest, but decifer fear from fatigue
        - Fear, anger, and despair sabotage us: take a small step forward
        - Ambition compels us: ambition tempts us to do something new so remove your freedom to do something else
        - Scatteredness confuses us: tasks are left undone because we dont know what is important to "us". "Somebody approaches us with a crisis- *their* crisis- which takes away from our time"
        - Overconfidence tricks us: an overestimation of our time and space: need to be honest with the time that we have.
    + Tie it up
        - Most of our task cannot be completed in one sitting, therefore us strategies to make coming back easier
        - collect all materials for the project in one place until you resume
        - jot down any thoughts that you want to remember
        - schedule the session to resume working on this task
        - communicate your progress to your partners or stakeholders
    + Always be unblocking
        - For major goal, project, mission always  ask yourself:
        - What is stopping me from moving forward?
        - What has stopped the process?
    + Combatting perfectionism
        - fear of failure or despair over its impending arrival
        - Striving for perfection and perfectionism is two different things: striver knows that it is not about creating something of high quality but about delivering something of high quality with all the constraints that it comes with
        - Exellence is quality delivered
    + Chunking time
        - break tasks into chunks of finishables
        - smaller goals lift the spirit because they make it easier for us to see
        - figure out discrete parts of the project
        - build your pause points with intentionality 
        - work intently towards those points
    + Intentional Breaks
        - Creative time needs room to breathe, treating it like a prison time is killing the creativity
        - We need mental, physical, and emotional breaks
        - During any creative session, take as many breaks as you like: on a piece of paper begin an intention break log. Have start, finish times and reason and how long the break was. For reason: mental- when you cant think, physical-bathroom or snacks, social- chats, work - other projects.Then calculate percentage of the time for the breaks


--NOTE FOR ME-- Just as you want to begin with the end or stopping point in mind you also watn to end with the beginning or resumption in mind. 


*Excellence is quality delivered*


#### Slowing down to speed up

*Commit to working smoothly and steadily. Use physical order to restore mental order. Don't rush.*


* Chef's don't run: if you are running you are not prepared.
* Chef's dont panic: sometimes it is the panic that is in your way than the task itself
* Precision before speed: slowing down helps precisive movement, and gives time to deconstruct the work
* Slow their bodies to slow time: state of physical space has effect on perception of time: work clean in our emotions
* Exercise:
    + Slow and steady movements
        - When you feel the urge to run elongate your movements
        - Practive interval breaths
        - Control the pace of your speech, talk slower
        - write down thoughts that occur; these may help with ideas of action
    + Task breakdown
        - Select a task that you often rush then
        - Perform action once; time it
        - Time you took to complete it; note resistance
        - List out steps for action; not too granular nor too broad between 5 to 10 steps
        - the breakdown tells you to create a process, fix a problem, or train yourself, slow down by scheduling time to these
* Habits:
    + Procrastination killer
        - slowing down gives power over procrastination
        - the more resistance towards something, slower you move but don't disengage
    + Make panic and crisis checklists
        - pick a situation that you fall apart in and create steps to remind you how to help with yourself
    + Cleaning reflex
        - in time of panic or stress clean your station or computer, keep your hands moving then chain your tasks together, and resume slowly


#### Open eyes and ears

* Balancing external and internal awareness